const cloud = require('wx-server-sdk')
cloud.init({ env: cloud.DYNAMIC_CURRENT_ENV })
const db = cloud.database()
const _ = db.command
const ok = data => ({ ok: true, data })
const fail = message => ({ ok: false, message })
const now = () => db.serverDate()
const MAX_MEMBERS = 5
const CATEGORIES = ['荤菜', '素菜', '汤羹', '主食', '快手菜', '儿童菜']
const FAMILY_AVATARS = ['🏡', '🏠', '🌳', '🌻', '🪴', '🧡']
const MEMBER_AVATARS = ['🧑‍🍳', '👩‍🍳', '👨‍🍳', '🧓', '👧', '🧒']

const RECOMMENDED_DISHES = [
  ['rec_tomato_egg','番茄炒蛋','🍳','#f4c8c1','快手菜',[['番茄','2个'],['鸡蛋','3个'],['小葱','1根']],['下饭','儿童友好'],['番茄切块，鸡蛋加少许盐打散。','热锅炒熟鸡蛋后盛出。','番茄炒出汁，倒回鸡蛋翻匀，撒葱花。'],'10分钟'],
  ['rec_cola_wings','可乐鸡翅','🍗','#f4d6b0','荤菜',[['鸡翅中','10个'],['可乐','1听'],['生姜','3片']],['下饭','家常'],['鸡翅两面煎至微黄。','加入姜片和可乐，没过鸡翅一半即可。','小火收汁至浓稠，按口味补少许生抽。'],'25分钟'],
  ['rec_garlic_green','蒜蓉青菜','🥗','#cfe7d1','素菜',[['当季青菜','1把'],['蒜','3瓣']],['清淡','快手'],['青菜洗净沥干，蒜切末。','热锅下蒜末爆香。','转大火下青菜，快速翻炒至断生。'],'5分钟'],
  ['rec_braised_pork','红烧肉','🥩','#eec8aa','荤菜',[['五花肉','500克'],['冰糖','20克'],['生姜','4片']],['经典','下饭'],['五花肉焯水后切块。','冰糖炒至焦糖色，下肉块翻匀上色。','加热水和姜片，小火焖至软糯后收汁。'],'70分钟'],
  ['rec_fish','清蒸鲈鱼','🐟','#cbe2ed','荤菜',[['鲈鱼','1条'],['生姜','5片'],['小葱','2根']],['清淡','宴客'],['鱼洗净，鱼身两侧划刀并铺姜片。','水开后上锅蒸 8 至 10 分钟。','倒掉蒸汁，铺葱丝，淋热油和蒸鱼豉油。'],'15分钟'],
  ['rec_soup','玉米排骨汤','🍲','#f2e5a9','汤羹',[['排骨','500克'],['玉米','1根'],['胡萝卜','1根']],['营养','清淡'],['排骨焯水洗净，玉米和胡萝卜切段。','所有食材加足量热水，大火煮开。','转小火炖 50 分钟，出锅前加盐。'],'60分钟'],
  ['rec_egg_soup','紫菜蛋花汤','🥣','#d9d5ef','汤羹',[['紫菜','1小把'],['鸡蛋','2个'],['小葱','1根']],['快手','清淡'],['锅中水烧开，放紫菜和少许虾皮。','鸡蛋打散，沿锅边慢慢淋入。','关火后撒葱花，调盐和香油。'],'8分钟'],
  ['rec_fried_rice','扬州炒饭','🍚','#f4d6b0','主食',[['米饭','2碗'],['鸡蛋','2个'],['火腿','100克'],['青豆','1把']],['快手','一锅出'],['鸡蛋炒散盛出，火腿切丁。','锅中炒香火腿和青豆。','下隔夜米饭压散，加入鸡蛋和调味翻匀。'],'12分钟'],
  ['rec_noodles','葱油拌面','🍜','#f2e5a9','主食',[['面条','2人份'],['小葱','1把'],['生抽','2勺']],['快手','省事'],['面条煮熟后过凉水，沥干备用。','小火把葱段炸至焦香。','葱油加入生抽和少许糖，和面条拌匀。'],'10分钟'],
  ['rec_potato_beef','土豆炖牛肉','🥘','#eec8aa','荤菜',[['牛肉','500克'],['土豆','2个'],['胡萝卜','1根']],['下饭','炖菜'],['牛肉焯水后炒香，加入姜和生抽。','加热水炖 40 分钟。','加入土豆、胡萝卜再炖至软烂，收汁调味。'],'60分钟'],
  ['rec_tofu','家常豆腐','🫕','#f4c8c1','素菜',[['豆腐','1块'],['青椒','1个'],['木耳','1把']],['下饭','家常'],['豆腐切片煎至两面金黄。','青椒和木耳下锅炒香。','放入豆腐，加生抽和少量水焖 3 分钟。'],'18分钟'],
  ['rec_steamed_egg','肉末蒸蛋','🍮','#f2e5a9','儿童菜',[['鸡蛋','3个'],['猪肉末','100克']],['儿童友好','软嫩'],['鸡蛋加 1.5 倍温水搅匀，滤去气泡。','肉末加少许生抽拌匀，铺在蛋液上。','盖盘蒸 10 分钟，焖 2 分钟再开盖。'],'18分钟'],
  ['rec_green_pepper_pork','青椒肉丝','🥩','#f4d6b0','荤菜',[['猪里脊','250克'],['青椒','2个'],['蒜','2瓣']],['下饭','快手'],['肉丝加淀粉和生抽抓匀，青椒切丝。','热锅滑熟肉丝盛出。','炒香蒜末和青椒，倒回肉丝翻匀。'],'12分钟'],
  ['rec_fish_flavor_pork','鱼香肉丝','🥕','#f4c8c1','荤菜',[['猪里脊','250克'],['木耳','1把'],['胡萝卜','1根']],['下饭','经典'],['肉丝抓匀腌制，配菜切丝。','调好糖、醋、生抽和少许豆瓣酱。','肉丝滑熟后炒香配菜，倒入鱼香汁收浓。'],'18分钟'],
  ['rec_kungpao_chicken','宫保鸡丁','🍗','#eec8aa','荤菜',[['鸡腿肉','300克'],['花生米','50克'],['黄瓜','1根']],['下饭','微辣'],['鸡肉切丁，加入淀粉和生抽抓匀。','干辣椒和花椒小火煸香。','下鸡丁和黄瓜快炒，最后拌入花生米。'],'18分钟'],
  ['rec_mapo_tofu','麻婆豆腐','🫕','#f4c8c1','素菜',[['嫩豆腐','1盒'],['猪肉末','80克'],['豆瓣酱','1勺']],['下饭','微辣'],['豆腐切小块，用淡盐水焯 1 分钟。','炒香肉末和豆瓣酱，加少许热水。','轻推豆腐煮 3 分钟，水淀粉勾薄芡。'],'15分钟'],
  ['rec_sour_potato','酸辣土豆丝','🥔','#f2e5a9','素菜',[['土豆','2个'],['青椒','1个'],['干辣椒','2个']],['快手','下饭'],['土豆切丝后泡水，冲去淀粉。','干辣椒和蒜末爆香。','大火炒土豆丝，沿锅边淋醋后加青椒。'],'10分钟'],
  ['rec_dry_fried_beans','干煸豆角','🫛','#cfe7d1','素菜',[['四季豆','300克'],['猪肉末','80克'],['芽菜','30克']],['下饭','家常'],['四季豆去筋切段，煸至表面起皱。','肉末炒散，加入芽菜和蒜末。','倒回豆角炒匀，调入生抽和少许糖。'],'20分钟'],
  ['rec_three_delicacies','地三鲜','🍆','#eec8aa','素菜',[['茄子','1根'],['土豆','1个'],['青椒','1个']],['下饭','家常'],['茄子、土豆切块，分别煎至金黄。','炒香蒜末和青椒。','倒入主料，加生抽、蚝油和少许水焖匀。'],'25分钟'],
  ['rec_tomato_brisket','番茄牛腩','🍅','#f4c8c1','荤菜',[['牛腩','500克'],['番茄','3个'],['洋葱','半个']],['炖菜','营养'],['牛腩焯水，番茄去皮切块。','洋葱炒香后加入番茄炒出汁。','放牛腩和热水炖软，最后加番茄块略煮。'],'80分钟'],
  ['rec_minced_noodles','蚂蚁上树','🍜','#d9d5ef','主食',[['粉丝','2把'],['猪肉末','100克'],['豆瓣酱','1勺']],['下饭','快手'],['粉丝温水泡软，肉末炒散。','加入豆瓣酱和少许热水煮开。','放粉丝吸收汤汁，撒葱花出锅。'],'15分钟'],
  ['rec_pepper_pork','小炒肉','🥓','#eec8aa','荤菜',[['五花肉','250克'],['青椒','3个'],['豆豉','1勺']],['下饭','家常'],['五花肉切薄片煸出油脂。','下豆豉、蒜片炒香。','加入青椒大火快炒，调入生抽。'],'15分钟'],
  ['rec_winter_melon_soup','冬瓜虾皮汤','🥣','#cbe2ed','汤羹',[['冬瓜','300克'],['虾皮','1把'],['小葱','1根']],['快手','清淡'],['冬瓜去皮切薄片。','虾皮煸香后加热水煮开。','下冬瓜煮至透明，撒葱花和白胡椒。'],'12分钟'],
  ['rec_eggplant','肉末茄子','🍆','#d9d5ef','荤菜',[['茄子','2根'],['猪肉末','120克'],['蒜','3瓣']],['下饭','家常'],['茄子切条煎软备用。','肉末炒散，加入蒜末和生抽。','放茄子和少许热水焖 3 分钟，撒葱花。'],'20分钟']
].map(([id,name,emoji,color,category,ingredients,tags,steps,cookTime]) => ({ _id:id,sourceType:'system',name,emoji,color,category,ingredients:ingredients.map(([name,amount])=>({name,amount})),tags,steps,cookTime,note:'' }))

async function member(openid) { const r=await db.collection('members').where({_openid:openid}).limit(1).get();return r.data[0]||null }
async function familyOf(openid) { const m=await member(openid);if(!m)return{member:null,family:null};const f=await db.collection('families').doc(m.familyId).get().catch(()=>null);return{member:m,family:f&&f.data} }
function code(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';return Array.from({length:6},()=>chars[Math.floor(Math.random()*chars.length)]).join('')}
async function uniqueCode(){for(let i=0;i<8;i++){const inviteCode=code();const r=await db.collection('families').where({inviteCode}).count();if(!r.total)return inviteCode}throw new Error('邀请码生成失败，请重试')}
function cleanAvatar(value,options,fallback){return options.includes(value)?value:fallback}
function cloudFileId(value){const fileId=String(value||'').trim();return fileId.startsWith('cloud://')&&fileId.length<=500?fileId:''}
function cleanDish(d){return{name:String(d.name||'').trim().slice(0,30),emoji:String(d.emoji||'🍲').slice(0,4),color:/^#[0-9a-f]{6}$/i.test(d.color||'')?d.color:'#f4d6b0',category:CATEGORIES.includes(d.category)?d.category:'快手菜',ingredients:Array.isArray(d.ingredients)?d.ingredients.slice(0,30).map(i=>({name:String(i.name||'').trim().slice(0,30),amount:String(i.amount||'').trim().slice(0,30)})).filter(i=>i.name):[],tags:Array.isArray(d.tags)?d.tags.slice(0,8).map(t=>String(t).trim().slice(0,12)).filter(Boolean):[],note:String(d.note||'').trim().slice(0,200)}}
function rec(id){return RECOMMENDED_DISHES.find(d=>d._id===id)}
async function familyDishes(familyId){const r=await db.collection('dishes').where({familyId,deleted:_.neq(true)}).orderBy('updatedAt','desc').get();return r.data.map(d=>({...d,sourceType:'family',category:d.category||'快手菜'}))}
async function resolveDishes(familyId,ids){const unique=[...new Set(Array.isArray(ids)?ids:[])].slice(0,20);const system=unique.map(rec).filter(Boolean);const customIds=unique.filter(id=>!String(id).startsWith('rec_'));let custom=[];if(customIds.length){const r=await db.collection('dishes').where({_id:_.in(customIds),familyId,deleted:_.neq(true)}).get();custom=r.data.map(d=>({...d,sourceType:'family'}))}const map=[...system,...custom].reduce((m,d)=>(m[d._id]=d,m),{});return unique.map(id=>map[id]).filter(Boolean)}
const snapshots=ds=>ds.map(d=>({_id:d._id,sourceType:d.sourceType||'family',name:d.name,emoji:d.emoji,color:d.color,category:d.category,ingredients:d.ingredients}))
function normalizePlan(p){if(!p)return null;if(Array.isArray(p.selections))return p;const ids=p.dishIds||[];return{...p,selections:ids.length?[{openid:p.updatedBy||'legacy',displayName:'历史菜单',dishIds:ids}]:[],confirmedDishIds:p.confirmedDishIds||ids}}
async function getPlan(familyId,date){const r=await db.collection('plans').where({familyId,date}).limit(1).get();return r.data[0]?normalizePlan(r.data[0]):null}
async function memberName(openid,familyId){const r=await db.collection('members').where({_openid:openid,familyId}).limit(1).get();return(r.data[0]&&r.data[0].displayName)||'家庭成员'}
async function catalog(familyId){const custom=await familyDishes(familyId);const since=new Date();since.setDate(since.getDate()-30);const r=await db.collection('plans').where({familyId,date:_.gte(since.toISOString().slice(0,10))}).limit(100).get();const stats={};r.data.forEach(raw=>{const p=normalizePlan(raw);(p.confirmedDishIds||[]).forEach(id=>{if(!stats[id])stats[id]={selectedCount30d:0,lastSelectedAt:''};stats[id].selectedCount30d++;if(!stats[id].lastSelectedAt||p.date>stats[id].lastSelectedAt)stats[id].lastSelectedAt=p.date})});const decorate=d=>({...d,...(stats[d._id]||{selectedCount30d:0,lastSelectedAt:''})});return{recommended:RECOMMENDED_DISHES.map(decorate),familyDishes:custom.map(decorate)}}

exports.main=async event=>{const{OPENID}=cloud.getWXContext();const action=event.action;try{
  if(action==='createFamily'){if(await member(OPENID))return fail('你已经加入了一个家庭');const inviteCode=await uniqueCode();const r=await db.collection('families').add({data:{name:String(event.name||'我们的家').trim().slice(0,20),avatar:FAMILY_AVATARS[0],inviteCode,ownerOpenid:OPENID,maxMembers:MAX_MEMBERS,createdAt:now()}});await db.collection('members').add({data:{_openid:OPENID,familyId:r._id,displayName:'管理员',avatar:MEMBER_AVATARS[0],role:'owner',joinedAt:now()}});return ok({familyId:r._id,inviteCode})}
  if(action==='joinFamily'){if(await member(OPENID))return fail('你已经加入了一个家庭');const f=await db.collection('families').where({inviteCode:String(event.inviteCode||'').toUpperCase()}).limit(1).get();if(!f.data.length)return fail('邀请码不存在');const count=await db.collection('members').where({familyId:f.data[0]._id}).count();if(count.total>=MAX_MEMBERS)return fail('这个家庭已经有 5 位成员');await db.collection('members').add({data:{_openid:OPENID,familyId:f.data[0]._id,displayName:`家庭成员${count.total+1}`,avatar:MEMBER_AVATARS[count.total%MEMBER_AVATARS.length],role:'member',joinedAt:now()}});return ok({familyId:f.data[0]._id})}
  const ctx=await familyOf(OPENID);const family=ctx.family
  if(action==='bootstrap'){if(!family)return ok({family:null});return ok({family,plan:await getPlan(family._id,event.date||new Date().toISOString().slice(0,10)),openid:OPENID,isOwner:family.ownerOpenid===OPENID})}
  if(action==='getProfile'){if(!family)return ok({family:null,members:[],openid:OPENID});const ms=await db.collection('members').where({familyId:family._id}).orderBy('joinedAt','asc').get();return ok({family:{...family,maxMembers:MAX_MEMBERS},members:ms.data,openid:OPENID,isOwner:family.ownerOpenid===OPENID})}
  if(!family)return fail('请先创建或加入家庭')
  if(action==='getToday'){const date=event.date||new Date().toISOString().slice(0,10);const plan=await getPlan(family._id,date);const c=await catalog(family._id);const all=[...c.recommended,...c.familyDishes];const map=all.reduce((m,d)=>(m[d._id]=d,m),{});const votes={};((plan&&plan.selections)||[]).forEach(s=>(s.dishIds||[]).forEach(id=>{if(!votes[id])votes[id]={dish:map[id]||((plan.dishSnapshots||[]).find(x=>x._id===id)),count:0,voters:[]};if(votes[id].dish){votes[id].count++;votes[id].voters.push(s.displayName||'家庭成员')}}));const confirmed=((plan&&plan.confirmedDishIds)||[]).map(id=>map[id]||((plan&&plan.dishSnapshots||[]).find(x=>x._id===id))).filter(Boolean);return ok({family,openid:OPENID,isOwner:family.ownerOpenid===OPENID,plan,voteDishes:Object.values(votes).sort((a,b)=>b.count-a.count),confirmedDishes:confirmed,recommendations:all.sort((a,b)=>(b.selectedCount30d||0)-(a.selectedCount30d||0)).slice(0,4)})}
  if(action==='getCatalog'){return ok({...await catalog(family._id),categories:CATEGORIES})}
  if(action==='favoriteDish'){const source=rec(event.id);if(!source)return fail('推荐菜不存在');const exists=await db.collection('dishes').where({familyId:family._id,sourceRecommendId:source._id,deleted:_.neq(true)}).limit(1).get();if(exists.data.length)return fail('已经收藏到我家菜谱');const r=await db.collection('dishes').add({data:{...cleanDish(source),familyId:family._id,sourceRecommendId:source._id,createdBy:OPENID,createdAt:now(),updatedAt:now()}});return ok({_id:r._id})}
  if(action==='getDish'){if(String(event.id).startsWith('rec_'))return ok(rec(event.id));const r=await db.collection('dishes').doc(event.id).get();if(r.data.familyId!==family._id)return fail('无权访问');return ok(r.data)}
  if(action==='saveDish'){const dish=cleanDish(event.dish||{});if(!dish.name||!dish.ingredients.length)return fail('菜名和食材不能为空');if(event.dish&&event.dish._id){const old=await db.collection('dishes').doc(event.dish._id).get();if(old.data.familyId!==family._id)return fail('无权修改');await db.collection('dishes').doc(event.dish._id).update({data:{...dish,updatedAt:now(),deleted:false}});return ok({_id:event.dish._id})}const r=await db.collection('dishes').add({data:{...dish,familyId:family._id,createdBy:OPENID,createdAt:now(),updatedAt:now()}});return ok({_id:r._id})}
  if(action==='deleteDish'){const old=await db.collection('dishes').doc(event.id).get();if(old.data.familyId!==family._id)return fail('无权删除');await db.collection('dishes').doc(event.id).update({data:{deleted:true,updatedAt:now()}});return ok({})}
  if(action==='getPlan'){const c=await catalog(family._id);const plan=await getPlan(family._id,event.date);const mine=((plan&&plan.selections)||[]).find(s=>s.openid===OPENID);return ok({family,dishes:[...c.familyDishes,...c.recommended],plan,myDishIds:(mine&&mine.dishIds)||[]})}
  if(action==='saveSelection'){const dishes=await resolveDishes(family._id,event.dishIds);const ids=dishes.map(d=>d._id);const existing=await getPlan(family._id,event.date);const selections=(existing&&existing.selections?existing.selections:[]).filter(s=>s.openid!==OPENID);selections.push({openid:OPENID,displayName:await memberName(OPENID,family._id),dishIds:ids,updatedAt:new Date()});const finalIds=[...new Set(selections.reduce((all,s)=>all.concat(s.dishIds||[]),[]))];const finalDishes=await resolveDishes(family._id,finalIds);const confirmedDishIds=finalDishes.map(d=>d._id);const data={selections,confirmedDishIds,dishIds:confirmedDishIds,dishSnapshots:snapshots(finalDishes),confirmedBy:'auto',confirmedAt:now(),updatedBy:OPENID,updatedAt:now()};if(existing)await db.collection('plans').doc(existing._id).update({data});else await db.collection('plans').add({data:{...data,familyId:family._id,date:event.date,createdAt:now()}});return ok({confirmedDishIds})}
  if(action==='confirmPlan'){if(family.ownerOpenid!==OPENID)return fail('只有家庭管理员可以确认最终菜单');const dishes=await resolveDishes(family._id,event.dishIds);const ids=dishes.map(d=>d._id);const existing=await getPlan(family._id,event.date);if(!existing)return fail('请先让家庭成员选菜');await db.collection('plans').doc(existing._id).update({data:{confirmedDishIds:ids,dishIds:ids,dishSnapshots:snapshots(dishes),confirmedBy:OPENID,confirmedAt:now(),updatedAt:now()}});return ok({})}
  if(action==='getShopping'){const plan=await getPlan(family._id,event.date);if(!plan)return ok({family,dishNames:[],items:[]});const state=await db.collection('shoppingStates').where({familyId:family._id,date:event.date}).limit(1).get();const checked=new Set(state.data.length?state.data[0].checkedNames:[]);const grouped={};(plan.dishSnapshots||[]).forEach(d=>(d.ingredients||[]).forEach(i=>{if(!grouped[i.name])grouped[i.name]=[];grouped[i.name].push(`${i.amount||'适量'}（${d.name}）`)}));return ok({family,dishNames:(plan.dishSnapshots||[]).map(d=>d.name),items:Object.keys(grouped).map(name=>({name,detail:grouped[name].join(' + '),checked:checked.has(name)}))})}
  if(action==='saveShopping'){const checkedNames=[...new Set(Array.isArray(event.checkedNames)?event.checkedNames.map(String):[])].slice(0,100);const e=await db.collection('shoppingStates').where({familyId:family._id,date:event.date}).limit(1).get();const data={checkedNames,updatedBy:OPENID,updatedAt:now()};if(e.data.length)await db.collection('shoppingStates').doc(e.data[0]._id).update({data});else await db.collection('shoppingStates').add({data:{...data,familyId:family._id,date:event.date}});return ok({})}
  if(action==='refreshInviteCode'){if(family.ownerOpenid!==OPENID)return fail('只有家庭管理员可以刷新邀请码');const inviteCode=await uniqueCode();await db.collection('families').doc(family._id).update({data:{inviteCode}});return ok({inviteCode})}
  if(action==='updateFamilyProfile'){if(family.ownerOpenid!==OPENID)return fail('只有家庭管理员可以编辑家庭资料');const name=String(event.name||'').trim().slice(0,20);if(!name)return fail('家庭名称不能为空');const avatar=cleanAvatar(event.avatar,FAMILY_AVATARS,FAMILY_AVATARS[0]);const coverImage=cloudFileId(event.coverImage);await db.collection('families').doc(family._id).update({data:{name,avatar,coverImage,updatedAt:now()}});return ok({name,avatar,coverImage})}
  if(action==='updateMyProfile'){const displayName=String(event.displayName||'').trim().slice(0,12);if(!displayName)return fail('昵称不能为空');const avatar=cleanAvatar(event.avatar,MEMBER_AVATARS,MEMBER_AVATARS[0]);const avatarImage=cloudFileId(event.avatarImage);await db.collection('members').doc(ctx.member._id).update({data:{displayName,avatar,avatarImage,updatedAt:now()}});return ok({displayName,avatar,avatarImage})}
  if(action==='removeMember'){if(family.ownerOpenid!==OPENID)return fail('只有家庭管理员可以移除成员');const target=await db.collection('members').doc(event.memberId).get();if(target.data.familyId!==family._id)return fail('成员不存在');if(target.data._openid===OPENID)return fail('不能移除自己');await db.collection('members').doc(event.memberId).remove();return ok({})}
  if(action==='transferOwner'){if(family.ownerOpenid!==OPENID)return fail('只有家庭管理员可以转让权限');const target=await db.collection('members').doc(event.memberId).get();if(target.data.familyId!==family._id)return fail('成员不存在');await db.collection('families').doc(family._id).update({data:{ownerOpenid:target.data._openid}});await db.collection('members').doc(ctx.member._id).update({data:{role:'member'}});await db.collection('members').doc(event.memberId).update({data:{role:'owner'}});return ok({})}
  if(action==='leaveFamily'){const ms=await db.collection('members').where({familyId:family._id}).get();if(family.ownerOpenid===OPENID&&ms.data.length>1)return fail('请先转让管理员后再退出');await db.collection('members').doc(ctx.member._id).remove();return ok({})}
  return fail('未知操作')
}catch(error){console.error(action,error);return fail(error.message||'服务暂时不可用')}}
