const { call } = require('../../utils/api')
Page({
  data:{family:{},members:[],openid:'',isOwner:false,editingMode:'',draftName:'',draftAvatar:'',draftImage:'',draftNameMax:12,avatarOptions:[],saving:false,familyAvatars:['🏡','🏠','🌳','🌻','🪴','🧡'],memberAvatars:['🧑‍🍳','👩‍🍳','👨‍🍳','🧓','👧','🧒']},onShow(){this.load()},
  async load(){try{const data=await call('getProfile');if(!data.family)return wx.redirectTo({url:'/pages/welcome/index'});this.setData(data)}catch(_){}},
  openSettings(e){const mode=e.currentTarget.dataset.mode;const mine=this.data.members.find(item=>item._openid===this.data.openid)||{};const isFamily=mode==='family';this.setData({editingMode:mode,draftName:isFamily?(this.data.family.name||''):(mine.displayName||''),draftAvatar:isFamily?(this.data.family.avatar||'🏡'):(mine.avatar||'🧑‍🍳'),draftImage:isFamily?(this.data.family.coverImage||''):(mine.avatarImage||''),draftNameMax:isFamily?20:12,avatarOptions:isFamily?this.data.familyAvatars:this.data.memberAvatars})},
  closeSettings(){this.setData({editingMode:''})},
  stopTap(){},
  onDraftName(e){this.setData({draftName:e.detail.value})},
  chooseAvatar(e){this.setData({draftAvatar:e.currentTarget.dataset.avatar})},
  async chooseImage(){try{const result=await wx.chooseMedia({count:1,mediaType:['image'],sizeType:['compressed']});const file=result.tempFiles&&result.tempFiles[0];if(!file)return;if(file.size>5*1024*1024)return wx.showToast({title:'图片请小于 5MB',icon:'none'});this.setData({draftImage:file.tempFilePath})}catch(_){}},
  async uploadImage(){const path=this.data.draftImage;if(!path||path.startsWith('cloud://'))return path;const extension=(path.match(/\.[a-zA-Z0-9]+$/)||['.jpg'])[0];const isFamily=this.data.editingMode==='family';const prefix=isFamily?`families/${this.data.family._id}/cover`:`members/${this.data.openid}/avatar`;const result=await wx.cloud.uploadFile({cloudPath:`${prefix}_${Date.now()}${extension}`,filePath:path});return result.fileID},
  async removeImage(){this.setData({draftImage:''})},
  async saveSettings(){if(this.data.saving)return;const isFamily=this.data.editingMode==='family';const mine=this.data.members.find(item=>item._openid===this.data.openid)||{};const oldImage=isFamily?this.data.family.coverImage:mine.avatarImage;this.setData({saving:true});try{const image=await this.uploadImage();const data=await call(isFamily?'updateFamilyProfile':'updateMyProfile',isFamily?{name:this.data.draftName,avatar:this.data.draftAvatar,coverImage:image}:{displayName:this.data.draftName,avatar:this.data.draftAvatar,avatarImage:image});if(oldImage&&oldImage!==image)wx.cloud.deleteFile({fileList:[oldImage]}).catch(()=>{});if(isFamily)this.setData({'family.name':data.name,'family.avatar':data.avatar,'family.coverImage':data.coverImage});else{const index=this.data.members.findIndex(item=>item._openid===this.data.openid);if(index>-1)this.setData({[`members[${index}].displayName`]:data.displayName,[`members[${index}].avatar`]:data.avatar,[`members[${index}].avatarImage`]:data.avatarImage})}this.closeSettings();wx.showToast({title:'已保存'})}catch(_){}finally{this.setData({saving:false})}},
  copyCode(){wx.setClipboardData({data:this.data.family.inviteCode})},
  refreshCode(){wx.showModal({title:'刷新邀请码？',content:'旧邀请码会立即失效。',success:async r=>{if(r.confirm){try{const data=await call('refreshInviteCode');this.setData({'family.inviteCode':data.inviteCode});wx.showToast({title:'已刷新'})}catch(_){}}}})},
  removeMember(e){const id=e.currentTarget.dataset.id;wx.showModal({title:'移除这位成员？',content:'移除后对方将无法查看家庭数据。',success:async r=>{if(r.confirm){try{await call('removeMember',{memberId:id});this.load()}catch(_){}}}})},
  transferOwner(e){const id=e.currentTarget.dataset.id;wx.showModal({title:'转让管理员？',content:'转让后对方可以管理成员和最终菜单。',success:async r=>{if(r.confirm){try{await call('transferOwner',{memberId:id});wx.showToast({title:'已转让'});this.load()}catch(_){}}}})},
  leave(){wx.showModal({title:'退出家庭？',content:'退出后将看不到共享菜谱和菜单。管理员需先转让权限。',success:async r=>{if(r.confirm){try{await call('leaveFamily');wx.redirectTo({url:'/pages/welcome/index'})}catch(_){}}}})}
})
